services:
  - type: web
    name: ytdl-api
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: python3 main.py --cookies cookies.txt
    envVars:
      - key: COOKIES_FILE
        value: cookies.txt
      - key: PROXY
        value: socks5://test:test@103.159.218.218:1920
